{{- if .Values.poddefault.enabled -}}
apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: add-minio-secret
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
 selector:
  matchLabels:
    add-minio-secret: "true"
 desc: "add minio-secret"
 env:
   - name: AWS_ACCESS_KEY_ID 
     valueFrom:
       secretKeyRef:
         name: {{ template "minio.name" . }} 
         key: accesskey
   - name: AWS_SECRET_ACCESS_KEY
     valueFrom:
       secretKeyRef:
         name: {{ template "minio.name" . }} 
         key: secretkey
{{- end }}
