apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: add-minio-secret
spec:
 selector:
  matchLabels:
    add-minio-secret: "true"
 desc: "add minio-secret"
 env:
   - name: AWS_ACCESS_KEY_ID 
     valueFrom:
       secretKeyRef:
         name: minio
         key: accesskey
   - name: AWS_SECRET_ACCESS_KEY
     valueFrom:
       secretKeyRef:
         name: minio
         key: secretkey
