ARG REPO=adamjm32
ARG ARCH
ARG BASE_CONTAINER=$REPO/kf-scipy-notebook-${ARCH}
FROM $BASE_CONTAINER
ARG ARCH=amd64

LABEL maintainer="Adam Makarucha"
USER $NB_UID
#Install python Machine learning libraries for processing large scale data processing (see https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/#/ for details )
RUN conda install --yes \
    powerai-cpu && \
    conda clean --all -f -y && \
    fix-permissions $HOME && \
    fix-permissions $CONDA_DIR

