ARG REPO=adamjm32
ARG ARCH
ARG VERSION
ARG BASE_CONTAINER=$REPO/kf-kubeflow-notebook-${ARCH}:$VERSION
FROM $BASE_CONTAINER
ARG ARCH=amd64

LABEL maintainer="Adam Makarucha"
USER $NB_UID
#Install python Machine learning libraries for processing large scale data processing (see https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/#/ for details )
ARG IBM_POWERAI_LICENSE_ACCEPT=yes
ENV IBM_POWERAI_LICENSE_ACCEPT=yes
RUN export IBM_POWERAI_LICENSE_ACCEPT=$IBM_POWERAI_LICENSE_ACCEPT && \
    conda install --yes \
    powerai-cpu=1.7.0 && \
    conda install --yes \
    beautifulsoup4 \
    bottleneck \
    ipympl \ 
    pandas=0.25.* \
    patsy \
    pytables \
    seaborn \
    sqlalchemy \
    statsmodels \
    sympy \
    vincent \
    xlrd && \
    conda clean --all -f -y && \
    fix-permissions $HOME && \
    fix-permissions $CONDA_DIR

