ARG BASE_CONTAINER=adamjm32/kf-scipy-notebook
FROM $BASE_CONTAINER
ARG ARCH=amd64

LABEL maintainer="Adam Makarucha"

#Install python Machine learning libraries for processing large scale data processing (see https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/#/ for details )
RUN conda create --name powerai && eval "$(conda shell.bash hook |sed 's/base/powerai/g')" && \
    conda install --quiet --yes -n powerai \
    powerai && \
    conda clean --all -f -y 

