ARG REPO=adamjm32
ARG BASE_CONTAINER=$REPO/kf-scipy-notebook
FROM $BASE_CONTAINER
ARG ARCH=amd64

LABEL maintainer="Adam Makarucha"
USER root
#Install python Machine learning libraries for processing large scale data processing (see https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/#/ for details )
RUN eval "$(conda shell.bash hook |sed 's/base/wmlce/g')" && \
    conda install --yes -n wmlce \
    powerai && \
    conda clean --all -f -y 

USER jovyan

