ARG BASE_CONTAINER=adamjm32/kf-machine-learning-notebook-gpu
FROM $BASE_CONTAINER
ARG ARCH=amd64

LABEL maintainer="Adam Makarucha"

USER root

## Compile CUDF from source to enable it to work with existing dependancies
ENV DEBIAN_FRONTEND=noninteractive

ARG CC=5
ARG CXX=5
RUN apt update -y --fix-missing && \
    apt upgrade -y && \
    apt install -y \
      git \
      gcc-${CC} \
      g++-${CXX} \
      build-essential \
      libboost-all-dev \
      tzdata

# Install conda
# Enables "source activate conda"


USER $NB_UID

COPY cudf_dev_cuda10.2_${ARCH}.yml /tmp/cudf_environment.yml
# Get CUDF

RUN eval "$(conda shell.bash hook |sed 's/base/wmlce/g')" && \
    conda install --quiet --yes -n wmlce "python-graphviz=0.13.2" "streamz=0.5.2" && \
    conda env update --prefix /opt/anaconda/envs/wmlce --file /tmp/cudf_environment.yml  --prune && \
    conda clean --all -f -y && \
    pip install cupy-cuda102 && \
    fix-permissions $HOME && \
    fix-permissions $CONDA_DIR

#RUN eval "$(conda shell.bash hook |sed 's/base/wmlce/g')" && \
    #mkdir /cupy && \
    #git clone https://github.com/cupy/cupy.git /cupy && \
    #cd /cupy && \
    #git checkout -b v8.0.0a1 && \

RUN eval "$(conda shell.bash hook |sed 's/base/wmlce/g')" && \
    mkdir /tmp/rmm && \
    git clone --recurse-submodules https://github.com/rapidsai/rmm.git /tmp/rmm && \
    cd /tmp/rmm && \
    mkdir build && \
    cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX && \
    make -j 4 && \
    make install && \
    cd /tmp/rmm/python && \
    python setup.py build_ext --inplace && \
    python setup.py install && \
    fix-permissions $HOME && \
    fix-permissions $CONDA_DIR

RUN eval "$(conda shell.bash hook |sed 's/base/wmlce/g')" && \
    mkdir /tmp/cudf && \
    git clone https://github.com/rapidsai/cudf.git /tmp/cudf && \
    cd /tmp/cudf && \
    git checkout -b branch-0.12 && \
    git submodule update --init --remote --recursive && \
    cd /tmp/cudf/cpp && \
    mkdir build && \
    cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_CXX11_ABI=ON && \
    make -j 4 && \
    make install && \
    cd /tmp/cudf/python/nvstrings && \
    python setup.py install && \
    cd /tmp/cudf/python/cudf && \
    python setup.py build_ext --inplace && \
    python setup.py install && \
    cd /tmp/cudf/python/dask_cudf && \
    python setup.py install && \
    fix-permissions $HOME && \
    fix-permissions $CONDA_DIR