ARG ARCH
ARG VERSION
ARG BASE_CONTAINER=adamjm32/kf-machine-learning-notebook-gpu-${ARCH}:$VERSION
FROM $BASE_CONTAINER
ARG ARCH=amd64
LABEL maintainer="Adam Makarucha"

USER root

## Compile CUDF from source to enable it to work with existing dependancies
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update -y --fix-missing && \
    apt-get remove -y protobuf-compiler libprotoc-dev libprotobuf-dev && \
    apt upgrade -y && \
    apt install -y \
      git \
      build-essential \
      libboost-all-dev \
      tzdata \
      libgdal-dev \
      libedit-dev \
      gdal-bin \
      maven

# Install conda
# Enables "source activate conda


ARG CC=/usr/bin/gcc 
ARG CXX=/usr/bin/g++
ARG PARALLEL_LEVEL=128
ARG JAVA_HOME=/usr/lib/jvm/java-8-openjdk-ppc64el
ENV JAVA_HOME=$JAVA_HOME


USER root

RUN mkdir /tmp/cppzmq && \
    git clone https://github.com/zeromq/cppzmq.git /tmp/cppzmq && \
    cd /tmp/cppzmq && git checkout v4.5.0 && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make -j$PARALLEL_LEVEL && \
    make install && \
    mkdir /tmp/peg && cd /tmp/peg && wget https://www.piumarta.com/software/peg/peg-0.1.18.tar.gz && \
    tar xvf peg-0.1.18.tar.gz && cd peg-0.1.18/ && \
    make -j$PARALLEL_LEVEL && make install && \
    mkdir /tmp/libcypher && cd /tmp/libcypher && wget https://github.com/cleishm/libcypher-parser/releases/download/v0.6.1/libcypher-parser-0.6.1.tar.gz && \
    tar xvf libcypher-parser-0.6.1.tar.gz && cd libcypher-parser-0.6.1/ &&  ./configure && \
    make -j$PARALLEL_LEVEL clean check && \
    make install

USER $NB_UID

COPY cudf_dev_cuda10.2_$ARCH.yml /tmp/cudf_environment.yml
# Get CUDF

## Install Dependancies 

RUN eval "$(conda shell.bash hook |sed 's/base/base/g')" && \
    conda install --quiet --yes -n base "pyarrow=0.15.1" "arrow-cpp=0.15.1" "python-graphviz=0.14" "streamz=0.5.2" networkx python-louvain && \
    conda env update --file /tmp/cudf_environment.yml  --prune && \
    conda clean --all -f -y && \
    fix-permissions $HOME && \
    fix-permissions $CONDA_DIR


ARG RAI_VERSION=v0.14.0
ARG NUMBA_VERSION=0.49.1
ARG LLVMLITE_VERSION=v0.32.1
ARG LLVMDEV_VERSION=8.0.0
ARG CUPY_VERSION=7.6.0

RUN conda install -c numba llvmdev=$LLVMDEV_VERSION && \
    git clone git://github.com/numba/numba.git /tmp/numba && \
    git clone https://github.com/numba/llvmlite.git /tmp/llvmlite && \
    cd /tmp/llvmlite && git checkout $LLVMLITE_VERSION && \
    python setup.py build && python runtests.py && \
    python setup.py install && \
    cd /tmp/numba && git checkout $NUMBA_VERSION && \
    python setup.py build_ext --inplace && \
    python setup.py install && \
    pip install . && \
    pip install cupy==$CUPY_VERSION && \
    pip install JPype1 netifaces pyhive protobuf==3.8.0 && \
    fix-permissions $HOME && \
    fix-permissions $CONDA_DIR



COPY rmm_cmaketests_${RAI_VERSION}.patch /tmp/
COPY rmm_build_${RAI_VERSION}.patch /tmp/

RUN eval "$(conda shell.bash hook |sed 's/base/base/g')" && \
    mkdir /tmp/rmm && \
    git clone --recurse-submodules https://github.com/rapidsai/rmm.git /tmp/rmm && \
    cd /tmp/rmm && \
    git checkout $RAI_VERSION && \
    git submodule update --init --remote --recursive && \
    git apply /tmp/rmm_cmaketests_${RAI_VERSION}.patch && \
    git apply /tmp/rmm_build_${RAI_VERSION}.patch && \
    ./build.sh -v clean librmm && \
    ./build.sh -v rmm && \
    cd build && \ 
#    make test && \
    fix-permissions $HOME && \
    fix-permissions $CONDA_DIR

COPY cudf_arrow_version_update.patch /tmp/cudf_arrow_version_update.patch
COPY cudf_build.patch /tmp/cudf_build.patch
COPY cudf_cmake.patch /tmp/cudf_cmake.patch
COPY cudf_cfloat.patch /tmp/cudf_cfloat.patch
COPY cudf_setup_cmake.patch /tmp/cudf_setup_cmake.patch

RUN eval "$(conda shell.bash hook |sed 's/base/base/g')" && \
    mkdir /tmp/cudf && \
    git clone https://github.com/rapidsai/cudf.git /tmp/cudf && \
    cd /tmp/cudf && \
    git checkout $RAI_VERSION && \
    git submodule update --init --remote --recursive && \
    git apply /tmp/cudf_arrow_version_update.patch && \
    git apply /tmp/cudf_build.patch && \
    git apply /tmp/cudf_cmake.patch && \
    git apply /tmp/cudf_cfloat.patch && \
    git apply /tmp/cudf_setup_cmake.patch && \
    ./build.sh -v libnvstrings libcudf --allgpuarch && \
    ./build.sh -v nvstrings && \
    ./build.sh -v cudf && \
    ./build.sh -v dask_cudf && \
    fix-permissions $HOME && \
    fix-permissions $CONDA_DIR

COPY cuml_build_$RAI_VERSION.patch /tmp/cuml_build_$RAI_VERSION.patch
COPY cuml_add_cudart_${RAI_VERSION}.patch /tmp/cuml_add_cudart_${RAI_VERSION}.patch
COPY cuml_cpp.cmakelist.patch /tmp/cuml_cpp.cmakelist.patch
COPY cuml_cpp.comms.std.src.patch /tmp/cuml_cpp.comms.std.src.patch
COPY cuml_cpp.test.cmakelists.patch /tmp/cuml_cpp.test.cmakelists.patch
COPY cuml_setup.patch /tmp/cuml_setup.patch
COPY cuml_patches_${RAI_VERSION}.patch /tmp/cuml_patches_${RAI_VERSION}.patch

RUN eval "$(conda shell.bash hook |sed 's/base/base/g')" && \
    mkdir /tmp/cuml && \
    git clone https://github.com/rapidsai/cuml.git /tmp/cuml && \
    cd /tmp/cuml && \
    git checkout $RAI_VERSION && \
    git submodule update --init --remote --recursive && \
    git apply /tmp/cuml_patches_${RAI_VERSION}.patch && \
    ./build.sh libcuml -v --singlegpu --allgpuarch && \
    ./build.sh cuml --singlegpu 

RUN eval "$(conda shell.bash hook |sed 's/base/base/g')" && \
    mkdir /tmp/cugraph && \
    git clone https://github.com/rapidsai/cugraph.git /tmp/cugraph && \
    cd /tmp/cugraph && \
    git checkout $RAI_VERSION && \
    git submodule update --init --remote --recursive && \
    ./build.sh libcugraph -v && \
    ./build.sh cugraph -v && \
    fix-permissions $HOME && \
    fix-permissions $CONDA_DIR

ENV CUDF_HOME=/tmp/cudf
ARG CUDF_HOME=/tmp/cudf

RUN eval "$(conda shell.bash hook |sed 's/base/base/g')" && \
    mkdir /tmp/cuspatial && \
    git clone https://github.com/rapidsai/cuspatial.git /tmp/cuspatial && \
    cd /tmp/cuspatial && \
    git checkout $RAI_VERSION && \
    git submodule update --init --remote --recursive && \
    ./build.sh libcuspatial -v && \
    ./build.sh cuspatial -v && \
    fix-permissions $HOME && \
    fix-permissions $CONDA_DIR 

RUN eval "$(conda shell.bash hook |sed 's/base/base/g')" && \
    conda install --yes -n base -c conda-forge gtest gmock 

RUN eval "$(conda shell.bash hook |sed 's/base/base/g')" && \
    mkdir /tmp/blazingdb-toolchain && \
    git clone https://github.com/BlazingDB/blazingdb-toolchain.git /tmp/blazingdb-toolchain && \
    cd /tmp/blazingdb-toolchain && \
    git checkout $RAI_VERSION && \
    mkdir build-aws && \
    mkdir build-gcp && \
    cd build-gcp && \
    cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DBUILD_TARGET=gcp-cpp && \
    make -j$PARALLEL_LEVEL && \
    make install && \
    cd ../build-aws && \
    cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DBUILD_TARGET=aws-cpp && \
    make -j$PARALLEL_LEVEL && \
    make install 

COPY bdb-build.patch /tmp/bdb-build.patch

RUN mkdir -p /opt/anaconda/include/bsql-rapids-thirdparty/ && \
   DIR_BSQL="bsql-rapids-thirdparty" && \
cp -rf /tmp/cudf/thirdparty/cub /opt/anaconda/include/$DIR_BSQL/cub && \
rm -rf /tmp/cudf/thirdparty/libcudacxx/libcxx/test/ && \ 
cp -rf /tmp/cudf/thirdparty/libcudacxx /opt/anaconda/include/$DIR_BSQL/libcudacxx

USER root
RUN git clone https://github.com/gabime/spdlog.git /tmp/spdlog && \
    cd /tmp/spdlog && mkdir build && cd build && \
    cmake .. && make -j && make install
USER $NB_UID

RUN git clone https://github.com/dropbox/PyHive.git /tmp/PyHive && \ 
    git clone https://github.com/apache/thrift.git /tmp/thrift && \
    cd /tmp/thrift/lib/py/ && pip install . && \
    cd /tmp/PyHive && pip install . 

RUN git clone https://github.com/dask/dask.git /tmp/dask && \
   cd /tmp/dask && git checkout 2.16.0 && \
   python -m pip install .

COPY blazingsql_patches_${RAI_VERSION}.patch /tmp/blazingsql_patches_${RAI_VERSION}.patch

RUN eval "$(conda shell.bash hook |sed 's/base/base/g')" && \
    mkdir /tmp/blazingsql && \
    git clone https://github.com/BlazingDB/blazingsql.git /tmp/blazingsql && \
    cd /tmp/blazingsql && \
    git checkout $RAI_VERSION && \
    git submodule update --init --remote --recursive && \
    git apply /tmp/blazingsql_patches_${RAI_VERSION}.patch && \
    export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-ppc64el && \
    ./build.sh

ENV CONDA_PREFIX=/opt/anaconda
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-ppc64el 
USER root 
RUN mkdir /home/jovyan/.local  && chown -R $NB_UID:$NB_UID /home/jovyan/.local
USER $NB_UID


