ARG ARCH
ARG VERSION
ARG BASE_CONTAINER=adamjm32/kf-machine-learning-notebook-gpu-${ARCH}:$VERSION
FROM $BASE_CONTAINER
ARG ARCH=amd64

LABEL maintainer="Adam Makarucha"

USER root

## Compile CUDF from source to enable it to work with existing dependancies
ENV DEBIAN_FRONTEND=noninteractive

ARG CC=5
ARG CXX=5
RUN apt update -y --fix-missing && \
    apt upgrade -y && \
    apt install -y \
      git \
      gcc-${CC} \
      g++-${CXX} \
      build-essential \
      libboost-all-dev \
      tzdata

# Install conda
# Enables "source activate conda

ARG CC=gcc 
ARG CXX=g++



USER $NB_UID


RUN conda create --name rapids && eval "$(conda shell.bash hook |sed 's/base/rapids/g')" && \
    conda install -n rapids -c rapidsai -c nvidia -c conda-forge \
    -c defaults rapids=0.15 python=3.7 cudatoolkit=10.2 && \
    conda install --quiet --yes -n rapids 'ipykernel=5.1.4=py37h39e3cac_0' && \
    python -m ipykernel install --user --name rapids --display-name "Python (rapids)" && \
    conda clean --all -f -y && \
    fix-permissions $HOME && \
    fix-permissions $CONDA_DIR

RUN conda install -n rapids -c blazingsql/label/cuda10.2 -c blazingsql -c rapidsai -c nvidia -c conda-forge -c defaults blazingsql python=3.7 && \
    conda clean --all -f -y && \
    fix-permissions $HOME && \
    fix-permissions $CONDA_DIR


